version: '3.1'

services:
  mongo:
    container_name: 'mongo'
    image: mongo
    restart: always
    ports: 
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: alohomora
        MONGO_INITDB_DATABASE: user-loader

  mongo-express:
    container_name: 'mongo-express'
    image: mongo-express
    restart: always
    ports: 
        - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: alohomora
      ME_CONFIG_MONGODB_URL: mongodb://root:alohomora@mongo:27017/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    